#!/usr/bin/env bash

downloadCommitHook (){
    echo "The local version needs to be updated, start downloading ..."
    delete_result=`rm $workdir/commit-msg-*`
    download=`curl -o $workdir/$hook_name $1`
}

workdir=`cd $(dirname $0) ;pwd`
hook_name=""
hook_download_url="https://raw.githubusercontent.com/xiaoleiPENG/testRepo/master"
remove_version_url="https://gitee.com/letUsDoIt_925/rules/raw/master/commit_hook_version"
remote_version=`curl -s --connect-timeout 5 $remove_version_url`

if [ "$remote_version" == "" ]
then
    exit 0 
fi

unameOut="$(uname -s)"
case "${unameOut}" in
    Linux*)     machine=commit-hook-Linux-$remote_version;;
    Darwin*)    machine=commit-hook-Mac-$remote_version;;
    MINGW*)     machine=commit-hook-Win-$remote_version".exe";;
esac

if [ "$machine" == commit-hook-Win-$remote_version".exe" ]
then  
    hook_name="$machine"
    if [ ! -f "$workdir/$hook_name" ]; then
        downloadCommitHook "$hook_download_url/$hook_name"
    fi
else
    hook_name="$machine"
    if [ ! -f "$workdir/$hook_name" ]; then
        downloadCommitHook "$hook_download_url/$hook_name"
        chmod +x "$workdir/$hook_name"
    fi
fi

exec "$workdir/$hook_name"